version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-production
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: maiky
      MYSQL_USER: automate
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - my-network

  api:
    build: 
      context: ./maikyapi
      dockerfile: Dockerfile
    image: maiky/api
    ports:
      - "8080:8080"  # Host port 3500 mapped to container port 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=maiky;User=automate;Password=password;Port=3306;
    depends_on:
      - db
    networks:
      - my-network

  web:
    build: 
      context: ./maikyweb
      dockerfile: Dockerfile
    image: maiky/web
    ports:
      - "3000:3000"  # Host port 3000 mapped to container port 3000
    environment:
      - NEXTAUTH_URL=http://119.59.99.163:3000
      - NEXT_PUBLIC_API_URL=http://api:8080/api
    depends_on:
      - api
    restart: always
    networks:
      - my-network

volumes:
  mysql_data:

networks:
  my-network:
    driver: bridge
