services:
  testing:
    build:
      context: ./maikytest
      dockerfile: Dockerfile
    volumes:
      - ./reports:/opt/app/junit/
    command: npx cypress run --reporter junit --reporter-options mochaFile=/opt/app/junit/test-results.xml