version: '3.8'

services:
  api:
    build: 
      context: ./maikyapi
      dockerfile: Dockerfile.dev
    image: maiky/api
    ports:
      - "3501:8084"  # Host port 3500 mapped to container port 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=119.59.99.163;Database=maiky;User=automate;Password=password;Port=3307;
    networks:
      - my-network-test

  web:
    build: 
      context: ./maikyweb
      dockerfile: Dockerfile
    image: maiky/web
    ports:
      - "3000:3000"  # Host port 3000 mapped to container port 3000
    environment:
      - NEXTAUTH_URL=http://119.59.99.163:3000
      - NEXT_PUBLIC_API_URL=http://api:8084/api
    depends_on:
      - api
    restart: always
    networks:
      - my-network-test

volumes:
  mysql_data:

networks:
  my-network-test:
    driver: bridge
