services:
  testing:
    build:
      context: ./maikytest
      dockerfile: Dockerfile
    volumes:
      - ./reports:/opt/app/junit/
    environment:
      - CYPRESS_BASE_URL=http://127.0.0.1:8080
    command: npx cypress run --reporter junit --reporter-options mochaFile=/opt/app/junit/test-results.xml