version: "3.8"

services:
  nuxt-app:
    build: .
    container_name: maikyweb
    restart: always
    ports:
      - "3000:3000"
    command: "npm run dev"
    environment:
      - NODE_ENV=local
    networks:
      - my-network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
networks:
  my-network:
    driver: bridge