services: # Services to deploy
  
  dockerapp:
    image: maikyapi #image name, Default:- Folder Name
    build:
      dockerfile : Dockerfile # path to Dockerfile
    ports:
      - "3500:8080" # HOST_PORT:CONTAINER_PORT
    networks:
      - my-network

networks:
  my-network:
    driver: bridge